---
name: reviewdog
"on": pull_request
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: . .?*/**/*.{md,markdown}
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          pattern: |
            *.sh
            commit-msg
            pre-commit
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          files: >
            ["README.md", "CONTRIBUTING.md", "SECURITY.md",
            ".github/PULL_REQUEST_TEMPLATE.md", ".github/ISSUE_TEMPLATE",
            ".github/vale_styles/Microsoft"]
          reporter: github-pr-review
          # Let this CI fail here if Vale throws errors
          # because it's difficult to run Vale lint in Test workflow
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
